#!/usr/bin/env php
<?php
define('ROOTPATH', __DIR__ . DIRECTORY_SEPARATOR);
define('APPPATH', ROOTPATH . 'app' . DIRECTORY_SEPARATOR);
define('WRITEPATH', ROOTPATH . 'writable' . DIRECTORY_SEPARATOR);

require ROOTPATH . 'vendor/autoload.php';

$environment = getenv('CI_ENVIRONMENT') ?: 'development';

require APPPATH . 'Config/Constants.php';
require APPPATH . 'Config/Boot/' . $environment . '.php';
require APPPATH . 'Common.php';

$paths = new \Config\Paths();
define('SYSTEMPATH', realpath($paths->systemDirectory) . DIRECTORY_SEPARATOR);

\Config\Services::commands()->run();
